<a href="https://colab.research.google.com/github/zhonghaoyyds/Study-Notebook/blob/main/Pytorch/Pytorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Tutorial**


In [1]:
import torch

**1. Pytorch Documentation Explanation with torch.max**



In [2]:
x = torch.randn(4,5)
y = torch.randn(4,5)
z = torch.randn(4,5)
print(x)
print(y)
print(z)

tensor([[ 2.3186e-01, -1.1391e+00,  4.3116e-04, -7.5797e-01,  1.1005e+00],
        [ 1.2027e+00, -8.2492e-01, -4.6356e-01,  1.5151e-01, -3.8166e-01],
        [-9.7148e-01,  2.4800e-01,  7.9867e-01, -2.9770e-01, -1.1188e+00],
        [-6.9175e-01, -1.4921e-01, -1.1613e+00,  9.9082e-01, -8.3644e-01]])
tensor([[ 0.6430,  0.2247, -0.2756, -0.3365,  0.6045],
        [-0.0178,  1.1472, -0.8803, -1.0342,  0.5523],
        [-0.4520,  0.4303,  1.5063, -0.0269,  0.0831],
        [-0.3034, -1.0063, -0.2890,  0.2440, -1.3056]])
tensor([[ 0.1546,  0.5280, -1.3986,  1.2705,  0.4862],
        [-0.5550, -0.0095,  0.2336,  0.6994, -1.1295],
        [ 0.0945, -0.8418, -0.8285, -0.2093,  0.2601],
        [-1.3554,  0.3483,  1.3885, -0.5549, -0.1415]])


In [3]:
# 1. max of entire tensor (torch.max(input) → Tensor)
m = torch.max(x)
print(m)

tensor(1.2027)


In [4]:
# 2. max along a dimension (torch.max(input, dim, keepdim=False, *, out=None) → (Tensor, LongTensor))
m, idx = torch.max(x,0)
print(m)
print(idx)

tensor([1.2027, 0.2480, 0.7987, 0.9908, 1.1005])
tensor([1, 2, 2, 3, 0])


In [5]:
# 2-2
m, idx = torch.max(input=x,dim=0)
print(m)
print(idx)

tensor([1.2027, 0.2480, 0.7987, 0.9908, 1.1005])
tensor([1, 2, 2, 3, 0])


In [6]:
# 2-3
m, idx = torch.max(x,0,False)
print(m)
print(idx)

tensor([1.2027, 0.2480, 0.7987, 0.9908, 1.1005])
tensor([1, 2, 2, 3, 0])


In [7]:
# 2-4
m, idx = torch.max(x,dim=0,keepdim=True)
print(m)
print(idx)

tensor([[1.2027, 0.2480, 0.7987, 0.9908, 1.1005]])
tensor([[1, 2, 2, 3, 0]])


In [ ]:
# 2-5
p = (m,idx)
torch.max(x,0,False,out=p)
print(p[0])
print(p[1])


In [ ]:
# 2-6
p = (m,idx)
torch.max(x,0,False,p)
print(p[0])
print(p[1])

In [ ]:
# 2-7
m, idx = torch.max(x,True)

In [ ]:
# 3. max(choose max) operators on two tensors (torch.max(input, other, *, out=None) → Tensor)
t = torch.max(x,y)
print(t)



```
# 此内容为代码格式
```

**2. Common errors**



::The following code blocks show some common errors while using the torch library. First, execute the code with error, and then execute the next code block to fix the error. You need to change the runtime to GPU.


.to("cuda:n")表示资源或者模型放在第几个GPU上.


In [ ]:
import torch


tensor.to("cuda:n")表示资源或者模型放在第n个GPU上.

In [20]:
# 1. different device error
model = torch.nn.Linear(5,1).to("cuda:0")
x = torch.Tensor([1,2,3,4,5]).to("cpu")
y = model(x)

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)

:: 必须同一个GPU上，由于colab只有一个GPU，导致这里无法进行测试，多GPU测试

In [21]:
# 1. different device error (fixed)
x = torch.Tensor([1,2,3,4,5]).to("cuda:0")
y = model(x)
print(y.shape)

torch.Size([1])


::运行以下代码可以看到只有一个GPU

In [19]:
print(f"Available GPUs: {torch.cuda.device_count()}")

Available GPUs: 1


:: 这里是张量维度出现了混乱，虽然tensor张量支持广播，但是由于两个维度都不匹配，所以导致无法对齐

In [3]:
# 2. mismatched dimensions error
x = torch.randn(4,5)
y = torch.randn(5,4)
z = x + y

RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1

::这里是使用了tensor.transpose(dim0, dim1) , 其中dim参数是要交换的维度

In [4]:
# 2. mismatched dimensions error (fixed)
y= y.transpose(0,1)
z = x + y
print(z.shape)

torch.Size([4, 5])


:: 这里是由于GPU只有5.93GB，但是实际给模型输入的一个batch大小太大，导致无法计算，可以考虑降低一个batch中的样本数，增加batch数，从而减少一次batch的训练内存


In [1]:
# 3. cuda out of memory error
import torch
import torchvision.models as models
resnet18 = models.resnet18().to("cuda:0") # Neural Networks for Image Recognition
data = torch.randn(2048,3,244,244) # Create fake data (512 images)
out = resnet18(data.to("cuda:0")) # Use Data as Input and Feed to Model
print(out.shape)


OutOfMemoryError: CUDA out of memory. Tried to allocate 7.27 GiB. GPU 0 has a total capacity of 14.74 GiB of which 5.93 GiB is free. Process 2729 has 8.81 GiB memory in use. Of the allocated memory 8.67 GiB is allocated by PyTorch, and 19.31 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

:: 可以看到，把2048个样本分为2048个batch，注意此时一个batch d的维度为3，还需要再在d的前面加一个维度作为batch_size，即1.注意unsqueeze(dim)是在维度dim前在加一维

In [ ]:
# 3. cuda out of memory error (fixed)
for d in data:
  out = resnet18(d.to("cuda:0").unsqueeze(0))
print(out.shape)

torch.Size([1, 1000])


In [ ]:
# 4. mismatched tensor type
import torch.nn as nn
L = nn.CrossEntropyLoss()
outs = torch.randn(5,5)
labels = torch.Tensor([1,2,3,4,0])
lossval = L(outs,labels) # Calculate CrossEntropyLoss between outs and labels

RuntimeError: ignored

In [ ]:
# 4. mismatched tensor type (fixed)
labels = labels.long()
lossval = L(outs,labels)
print(lossval)

tensor(2.6215)


**3. More on dataset and dataloader**


A dataset is a cluster of data in a organized way. A dataloader is a loader which can iterate through the data set.

Let a dataset be the English alphabets "abcdefghijklmnopqrstuvwxyz"

In [ ]:
dataset = "abcdefghijklmnopqrstuvwxyz"

A simple dataloader could be implemented with the python code "for"

In [ ]:
for datapoint in dataset:
  print(datapoint)

When using the dataloader, we often like to shuffle the data. This is where torch.utils.data.DataLoader comes in handy. If each data is an index (0,1,2...) from the view of torch.utils.data.DataLoader, shuffling can simply be done by shuffling an index array.



torch.utils.data.DataLoader will need two imformation to fulfill its role. First, it needs to know the length of the data. Second, once torch.utils.data.DataLoader outputs the index of the shuffling results, the dataset needs to return the corresponding data.

Therefore, torch.utils.data.Dataset provides the imformation by two functions, `__len__()` and `__getitem__()` to support torch.utils.data.Dataloader

In [ ]:
import torch
import torch.utils.data
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"

  def __getitem__(self,idx): # if the index is idx, what will be the data?
    return self.data[idx]

  def __len__(self): # What is the length of the dataset
    return len(self.data)

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)

A simple data augmentation technique can be done by changing the code in `__len__()` and `__getitem__()`. Suppose we want to double the length of the dataset by adding in the uppercase letters, using only the lowercase dataset, you can change the dataset to the following.

In [ ]:
import torch.utils.data
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"

  def __getitem__(self,idx): # if the index is idx, what will be the data?
    if idx >= len(self.data): # if the index >= 26, return upper case letter
      return self.data[idx%26].upper()
    else: # if the index < 26, return lower case, return lower case letter
      return self.data[idx]

  def __len__(self): # What is the length of the dataset
    return 2 * len(self.data) # The length is now twice as large

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)